# ════════════════════════════════════════════════════════════════════════════
#  Self-signed certificate (generated by Terraform) + ACM import
#  Satisfies ELB-024 (HTTPS listener). Internal-only traffic.
# ════════════════════════════════════════════════════════════════════════════
resource "tls_private_key" "cert" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "cert" {
  private_key_pem = tls_private_key.cert.private_key_pem

  subject {
    common_name  = "reportiq-internal"
    organization = "S&P Global"
  }

  # SAN includes the ALB DNS name and friendly internal DNS name
  dns_names = [
    "reportiq-internal",
    aws_lb.app.dns_name,
    var.dns_name,
  ]

  validity_period_hours = 19800 # ~825 days
  early_renewal_hours   = 720

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
  ]
}

resource "aws_acm_certificate" "cert" {
  private_key      = tls_private_key.cert.private_key_pem
  certificate_body = tls_self_signed_cert.cert.cert_pem

  tags = { Name = "${local.name}-selfsigned" }

  lifecycle {
    create_before_destroy = true
  }
}

# ─── HTTPS listener on 443 (forwards to the app) ─────────────────────────────
resource "aws_lb_listener" "https" {
  load_balancer_arn = aws_lb.app.arn
  port              = 443
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-TLS13-1-2-2021-06"
  certificate_arn   = aws_acm_certificate.cert.arn

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.app.arn
  }
}

# ─── HTTP listener on 80 → redirect to 443 (ELB-024 compliant) ───────────────
resource "aws_lb_listener" "http_redirect" {
  load_balancer_arn = aws_lb.app.arn
  port              = 80
  protocol          = "HTTP"

  default_action {
    type = "redirect"
    redirect {
      protocol    = "HTTPS"
      port        = "443"
      status_code = "HTTP_301"
    }
  }
}
